name: Taaxdog-coding
region: syd

services:
- name: web
  environment_slug: node-js
  github:
    repo: TaaxDog/TAAXDOG-CODING
    branch: main
    deploy_on_push: true
  
  source_dir: /
  build_command: npm install --production=false && npx prisma generate && npm run build
  run_command: npm start
  
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb-fixed
  
  http_port: 3000
  
  routes:
  - path: /
  
  envs:
  # Core configuration
  - key: NODE_ENV
    value: "production"
  - key: PORT
    value: 3000
  - key: NEXTAUTH_URL
    value: "https://taxreturnpro.com.au"
  - key: NEXT_PUBLIC_API_URL
    value: "https://taxreturnpro.com.au"
  
  # Authentication secrets
  - key: NEXTAUTH_SECRET
    value: ${NEXTAUTH_SECRET}
  - key: JWT_SECRET_KEY
    value: ${JWT_SECRET_KEY}
  - key: GOOGLE_CLIENT_ID
    value: ${GOOGLE_CLIENT_ID}
  - key: GOOGLE_CLIENT_SECRET
    value: ${GOOGLE_CLIENT_SECRET}
  
  # Database
  - key: DATABASE_URL
    value: ${DATABASE_URL}
  - key: DATABASE_POOLING_URL
    value: ${DATABASE_POOLING_URL}
  
  # Stripe (Live keys)
  - key: STRIPE_PUBLISHABLE_KEY
    value: ${STRIPE_PUBLISHABLE_KEY}
  - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
    value: ${STRIPE_PUBLISHABLE_KEY}
  - key: STRIPE_SECRET_KEY
    value: ${STRIPE_SECRET_KEY}
  - key: STRIPE_WEBHOOK_SECRET
    value: ${STRIPE_WEBHOOK_SECRET}
  - key: STRIPE_EARLY_ACCESS_PRICE_ID_SMART
    value: ${STRIPE_EARLY_ACCESS_PRICE_ID_SMART}
  - key: STRIPE_PRICE_ID_SMART
    value: ${STRIPE_PRICE_ID_SMART}
  - key: STRIPE_EARLY_ACCESS_PRICE_ID_PRO
    value: ${STRIPE_EARLY_ACCESS_PRICE_ID_PRO}
  - key: STRIPE_PRICE_ID_PRO
    value: ${STRIPE_PRICE_ID_PRO}
  
  # AI Services
  - key: ANTHROPIC_API_KEY
    value: ${ANTHROPIC_API_KEY}
  - key: OPENROUTER_API_KEY
    value: ${OPENROUTER_API_KEY}
  - key: GEMINI_API_KEY
    value: ${GEMINI_API_KEY}
  
  # Banking Integration
  - key: BASIQ_API_KEY
    value: ${BASIQ_API_KEY}
  - key: BASIQ_SERVER_URL
    value: "https://au-api.basiq.io"
  
  # Email Service
  - key: SENDGRID_API_KEY
    value: ${SENDGRID_API_KEY}
  - key: FROM_EMAIL
    value: "noreply@taxreturnpro.com.au"
  - key: SUPPORT_EMAIL
    value: "support@taxreturnpro.com.au"
  
  # Security & Compliance
  - key: FIELD_ENCRYPTION_KEY
    value: ${FIELD_ENCRYPTION_KEY}
  - key: COMPLIANCE_TEST_MODE
    value: "false"
  - key: AUSTRAC_API_KEY
    value: ${AUSTRAC_API_KEY}
  - key: ABN_LOOKUP_GUID
    value: ${ABN_LOOKUP_GUID}
  
  # Monitoring
  - key: SENTRY_DSN
    value: ${SENTRY_DSN}
  - key: SENTRY_ORG
    value: ${SENTRY_ORG}
  - key: SENTRY_PROJECT
    value: ${SENTRY_PROJECT}
  - key: NEXT_PUBLIC_SENTRY_DSN
    value: ${SENTRY_DSN}
  
  # Additional services
  - key: NEXT_PUBLIC_FIREBASE_API_KEY
    value: ${NEXT_PUBLIC_FIREBASE_API_KEY}
  - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    value: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
  - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
    value: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
  - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
    value: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
  - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
    value: ${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
  - key: NEXT_PUBLIC_FIREBASE_APP_ID
    value: ${NEXT_PUBLIC_FIREBASE_APP_ID}
  - key: FIREBASE_SERVICE_ACCOUNT_KEY
    value: ${FIREBASE_SERVICE_ACCOUNT_KEY}
  
  # Cache & Performance
  - key: REDIS_URL
    value: ${REDIS_URL}
  - key: ENABLE_CACHE
    value: "true"
  - key: CACHE_TTL
    value: "3600"
  
  # Feature Flags
  - key: FEATURE_AI_ENABLED
    value: "true"
  - key: FEATURE_BANKING_ENABLED
    value: "true"
  - key: FEATURE_RECEIPTS_ENABLED
    value: "true"
  - key: FEATURE_GOALS_ENABLED
    value: "true"
  
  # Flask Backend
  - key: FLASK_API_URL
    value: "http://flask-backend:5000"
  - key: FLASK_API_KEY
    value: ${FLASK_API_KEY}

domains:
- domain: taxreturnpro.com.au
  type: PRIMARY
- domain: www.taxreturnpro.com.au
  type: ALIAS

alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
- rule: DEPLOYMENT_LIVE