name: taaxdog-production
region: syd
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: TaaxDog/TAAXDOG-CODING
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: taaxdog
  run_command: npm start
  source_dir: /